# Generated by Django 2.2.5 on 2022-01-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('time', models.DateTimeField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
